input_a = input("مجموعه اول را وارد کنید (اعداد با فاصله): ")
input_b = input("مجموعه دوم را وارد کنید (اعداد با فاصله): ")
input_c = input("مجموعه سوم را وارد کنید (اعداد با فاصله): ")

set_a = set(map(int, input_a.split()))
set_b = set(map(int, input_b.split()))
set_c = set(map(int, input_c.split()))

intersection_all = set_a.intersection(set_b, set_c)
union_all = set_a.union(set_b, set_c)
only_in_a = set_a.difference(set_b.union(set_c))
common_b_c = set_b.intersection(set_c)
common_b_c_not_a = common_b_c.difference(set_a)
unique_to_a = set_a.difference(set_b.union(set_c))
unique_to_b = set_b.difference(set_a.union(set_c))
unique_to_c = set_c.difference(set_a.union(set_b))

print(intersection_all)
print(union_all)
print(only_in_a)
print(common_b_c_not_a)
print(unique_to_a)
print(unique_to_b)
print(unique_to_c)
